include "application.conf"

play.filters.hosts.allowed = [
  ".up.railway.app"
]

db.default.host = ${?PGHOST}
db.default.port = ${?PGPORT}
db.default.name = ${?PGDATABASE}

db.default.url = "jdbc:postgresql://"${db.default.host}":"${db.default.port}"/"${db.default.name}

db.default.username = ${?PGUSER}
db.default.password = ${?PGPASSWORD}

play.filters.enabled += "play.filters.cors.CORSFilter"
play.filters.cors.allowedOrigins = [ ${?CORS_ALLOWED_ORIGIN} ]
play.filters.cors.allowedHttpHeaders = [ "Accept", "Content-Type", "Authorization" ]
play.filters.cors.allowedMethods = [ "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS" ]
