# conf/application.conf

play.http.secret.key = ${?APPLICATION_SECRET}

play.filters.hosts.allowed = [
  "localhost",
  "127.0.0.1",
  "::1",
  ".up.railway.app",
]

play.filters.csrf {
  exempt {
    pathPatterns = ["/api/game/.*", "/api/state"]
  }
}

play.i18n.langs = [ "en" ]
play.modules.enabled += "modules.Module"
play.filters.disabled += "play.filters.csrf.CSRFFilter"

play.server.http.port = ${?PORT}

supabase.jwt.jwksUrl = ${?SUPABASE_JWKS_URL}
supabase.jwt.secret  = ${?SUPABASE_JWT_SECRET}

db.default.driver = "org.postgresql.Driver"
db.default.url = "jdbc:postgresql://localhost:5432/soccercardclash"
db.default.username = "postgres"
db.default.password = "postgres"
play.evolutions.enabled = true
play.evolutions.autoApply = true
