include "application.conf"

play.filters.hosts.allowed += ".up.railway.app"

db.default.driver = "org.postgresql.Driver"
db.default.url = "jdbc:postgresql://"${?PGHOST}":"${?PGPORT}"/"${?PGDATABASE}
db.default.username = ${?PGUSER}
db.default.password = ${?PGPASSWORD}

db.default.hikaricp.connectionTimeout = 60000
db.default.hikaricp.initializationFailTimeout = -1

play.filters.enabled += "play.filters.cors.CORSFilter"
play.filters.cors.allowedOrigins = [ ${?CORS_ALLOWED_ORIGIN} ]
play.filters.cors.allowedHttpHeaders = [ "Accept", "Content-Type", "Authorization" ]
play.filters.cors.allowedMethods = [ "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS" ]
play.filters.cors.supportsCredentials = true

play.http.session.sameSite = "None"
play.http.session.secure = true
