# conf/application.conf
play.http.secret.key = ${?APPLICATION_SECRET}

play.filters.hosts.allowed = [
  "localhost",
  "127.0.0.1",
  "::1",

  ".up.railway.app",

  # later: real domain :)
  # "www.soccercardclash.com"
]

play.filters.csrf {
  exempt {
    pathPatterns = ["/api/game/.*", "/api/state"]
  }
}

play.i18n.langs = [ "en" ]

play.modules.enabled += "modules.Module"
play.filters.disabled += "play.filters.csrf.CSRFFilter"
app.auth.devAnonymous = true

play.server.http.port = ${?PORT}

play.evolutions.enabled = true
play.evolutions.autoApply = true

supabase.jwt.secret = "dev-local-secret-change-me"

db.default.driver = "org.postgresql.Driver"

# local
db.default.url = "jdbc:postgresql://localhost:5432/scc_local"
db.default.username = "postgres"
db.default.password = "postgres"