# conf/application.conf
play.http.secret.key = ${?APPLICATION_SECRET}
play.http.secret.key = ${play.http.secret.key}


play.filters.hosts.allowed = [
  "localhost",
  "127.0.0.1",
  "::1",

  ".up.railway.app",

  # later: real domain :)
  # "www.soccercardclash.com"
]

play.filters.csrf {
  exempt {
    pathPatterns = ["/api/game/.*", "/api/state"]
  }
}

play.i18n.langs = [ "en" ]

play.modules.enabled += "modules.Module"
play.filters.disabled += "play.filters.csrf.CSRFFilter"
app.auth.devAnonymous = true

play.server.http.port = ${?PORT}


# Example: use DATABASE_URL from Railway Postgres
# DATABASE_URL will look like: postgres://user:pass@host:port/db
db.default.url = "jdbc:${?DATABASE_URL}"
db.default.driver = "org.postgresql.Driver"

# Optional: only enable DB if you actually use it immediately
# (we can refine once we add real account storage)
