include "application.conf"

db.default.driver = "org.postgresql.Driver"
db.default.url =
  "jdbc:postgresql://"${?PGHOST}":"${?PGPORT}"/"${?PGDATABASE}
db.default.username = ${?PGUSER}
db.default.password = ${?PGPASSWORD}

supabase.jwt.secret = ${SUPABASE_JWT_SECRET}
